GET http://localhost:3001/api/positions HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/position HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/position/:positionID HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/position/:positionID/changeID HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3001/api/position/:positionID HTTP/1.1
content-type: application/json

###