GET http://localhost:3001/api/skus HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/skus HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/skus/:id
HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/sku HTTP/1.1
content-type: application/json

###

PUT http://localhost:3001/api/sku/:id HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/sku/:id/position HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3001/api/skus/:id HTTP/1.1
content-type: application/json



