GET http://localhost:3001/api/testDescriptors HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/testDescriptors/:id HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/testDescriptor HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/testDescriptor/:id HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3001/api/testDescriptor/:id HTTP/1.1
content-type: application/json

###