GET http://localhost:3001/api/skuitems/:rfid/testResults HTTP/1.1
content-type: application/json

###
GET http://localhost:3001/api/skuitems/:rfid/testResults/:id HTTP/1.1
content-type: application/json

###
POST http://localhost:3001/api/skuitems/testResult HTTP/1.1
content-type: application/json

###
PUT http://localhost:3001/api/skuitems/:rfid/testResult/:id HTTP/1.1
content-type: application/json

###
DELETE http://localhost:3001/api/skuitems/:rfid/testResult/:id HTTP/1.1
content-type: application/json

###